development:
  adapter: postgresql
  encoding: unicode
  database: shrinkwrap_development
  pool: 5
  username: shrinkwrap
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: shrinkwrap_test
  pool: 5
  username: shrinkwrap
  password: