development:
  adapter: postgresql
  encoding: unicode
  database: shrinkwrap_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: shrinkwrap_test
  pool: 5
  host: localhost
